package com.podo.coinchatbot.app.model;


public enum Menu {
    MAIN,
    INVEST_CONFIG,
    COIN_COUNT_CONFIG,

    TARGET_ALARM_CONFIG,
    TARGET_ALARM_ADD,
    TARGET_ALARM_DELETE,

    MARKET_CONFIG,
    DAYLOOP_ALARM_CONFIG,
    TIMELOOP_ALARM_CONFIG,

    SUGGEST_MESSAGE,
    STOP_ALL_ALARM,
    HAPPY_COIN_PRICE,
    PREFERENCE,
    PREFERENC_LANGUAGE,
    PREFERENCE_LOCALTIME;


}
